import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import "katex/dist/katex.min.css";
import {
  createGraph,
  aiCreateJob,
  aiCancelJob,
  aiGetJob,
  aiStoreInputImage,
  cancelGraphWebSession,
  completeGraphWebSession,
  deleteGraph,
  duplicateGraph,
  getGraph,
  listGraphVersions,
  insertGraphToProject,
  listGraphs,
  listProjects,
  saveGraphExports,
  restoreGraphVersion,
  updateGraph,
} from "../api";
import { ConflictError, graphFileUrl, isTauri } from "../transport";
import { useApp } from "../store";
import type {
  AiGraphStructuredResult,
  AiJob,
  CompleteGraphWebSessionResult,
  GraphVersionSummary,
  GraphWebSession,
  ProjectSummary,
  StoredGraph,
  StoredGraphSummary,
} from "../types";
import { Modal } from "./ui";
import { PdfCanvasViewer } from "./PdfCanvasViewer";
import { SpatialGeometryEditor } from "../graph-editor/3d/SpatialGeometryEditor";
import { createTextbookCube, parseSpatialDocument, serializeSpatialDocument } from "../graph-editor/3d/model";

import type {
  ExprItem,
  MathLabel,
  PaperSettings,
  PointItem,
  Project,
  ViewRange,
  ParseResult,
} from "../../../mathgraph-pdf-studio/src/types";
import { parseExpression } from "../../../mathgraph-pdf-studio/src/lib/parser";
import type { RenderItem } from "../../../mathgraph-pdf-studio/src/lib/buildSvg";
import {
  buildExportSvg,
  buildPdf,
  svgFileContent,
  svgToPngBytes,
} from "../../../mathgraph-pdf-studio/src/lib/export";
import {
  defaultExprItem,
  defaultLabel,
  deserializeProject,
  newId,
  sampleProject,
  serializeProject,
} from "../../../mathgraph-pdf-studio/src/lib/project";
import { graphAspectRatio } from "../../../mathgraph-pdf-studio/src/lib/aspect";
import { initMathJax } from "../../../mathgraph-pdf-studio/src/lib/mathlabel";
import type { Intersection } from "../../../mathgraph-pdf-studio/src/lib/intersections";
import ExpressionPanel from "../../../mathgraph-pdf-studio/src/components/ExpressionPanel";
import GraphView from "../../../mathgraph-pdf-studio/src/components/GraphView";
import SettingsPanel from "../../../mathgraph-pdf-studio/src/components/SettingsPanel";
import "./graphs.css";

type EditorRecord = { id: string; title: string; version: number; sourceType: StoredGraphSummary["sourceType"] };
type GraphAiMode = "graph-from-text" | "graph-from-image" | "graph-from-problem";

function isGraphResult(value: AiJob["structuredResult"]): value is AiGraphStructuredResult {
  return !!value && "kind" in value && value.kind === "graph";
}

function blankProject(): Project {
  const sample = sampleProject();
  return {
    ...sample,
    expressions: [defaultExprItem("y = x^2", 0)],
    points: [],
    labels: [],
    paper: { ...sample.paper, title: "", problemNumber: "", caption: "" },
  };
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  }
  return btoa(binary);
}

function downloadBytes(name: string, bytes: Uint8Array, type: string) {
  const url = URL.createObjectURL(new Blob([bytes as BlobPart], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 2_000);
}

function downloadText(name: string, text: string, type: string) {
  downloadBytes(name, new TextEncoder().encode(text), type);
}

function downloadUrl(url: string) {
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.rel = "noopener";
  anchor.click();
}

function safeFileBase(title: string) {
  const value = title.trim().replace(/[<>:"/\\|?*\u0000-\u001f]/g, "_").replace(/[. ]+$/g, "");
  return (value || "graph").slice(0, 80);
}

function projectToPgfplots(project: Project): string {
  const plots: string[] = [];
  for (const expression of project.expressions) {
    if (!expression.visible) continue;
    const match = expression.input.trim().match(/^y\s*=\s*(.+)$/i);
    if (!match) {
      plots.push(`% Unsupported expression retained in graph.json: ${expression.input.replace(/[\r\n]/g, " ")}`);
      continue;
    }
    const expr = match[1]
      .replace(/\^/g, "^")
      .replace(/\bln\s*\(/gi, "ln(")
      .replace(/\babs\s*\(/gi, "abs(");
    const color = expression.color.replace("#", "");
    const dashed = expression.lineStyle === "dashed" ? ", dashed" : "";
    plots.push(`\\addplot[domain=${project.range.xmin}:${project.range.xmax}, samples=240, color={rgb,255:red,${parseInt(color.slice(0, 2), 16)};green,${parseInt(color.slice(2, 4), 16)};blue,${parseInt(color.slice(4, 6), 16)}}, line width=${Math.max(0.4, expression.lineWidth * 0.35).toFixed(2)}pt${dashed}] {${expr}};`);
  }
  return [
    "% Generated by 教材工房 / MathGraph PDF Studio shared core",
    "% Required packages: \\usepackage{pgfplots}",
    "\\begin{tikzpicture}",
    "\\begin{axis}[",
    `  xmin=${project.range.xmin}, xmax=${project.range.xmax},`,
    `  ymin=${project.range.ymin}, ymax=${project.range.ymax},`,
    `  grid=${project.paper.showGrid ? "major" : "none"}, axis lines=${project.paper.showAxes ? "middle" : "none"},`,
    `  xtick distance=${project.range.xstep}, ytick distance=${project.range.ystep},`,
    "  width=0.72\\linewidth, compat=1.18",
    "]",
    ...plots,
    "\\end{axis}",
    "\\end{tikzpicture}",
    "",
  ].join("\n");
}

// 依存ライブラリを増やさず、端末保存用のstore方式ZIPを生成する。
function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function u16(value: number) {
  return [value & 255, (value >>> 8) & 255];
}

function u32(value: number) {
  return [value & 255, (value >>> 8) & 255, (value >>> 16) & 255, (value >>> 24) & 255];
}

function makeZip(files: Array<{ name: string; bytes: Uint8Array }>): Uint8Array {
  const encoder = new TextEncoder();
  const local: Uint8Array[] = [];
  const central: Uint8Array[] = [];
  let offset = 0;
  for (const file of files) {
    const name = encoder.encode(file.name);
    const crc = crc32(file.bytes);
    const header = new Uint8Array([
      ...u32(0x04034b50), ...u16(20), ...u16(0), ...u16(0), ...u16(0), ...u16(0),
      ...u32(crc), ...u32(file.bytes.length), ...u32(file.bytes.length), ...u16(name.length), ...u16(0),
      ...name,
    ]);
    local.push(header, file.bytes);
    central.push(new Uint8Array([
      ...u32(0x02014b50), ...u16(20), ...u16(20), ...u16(0), ...u16(0), ...u16(0), ...u16(0),
      ...u32(crc), ...u32(file.bytes.length), ...u32(file.bytes.length), ...u16(name.length),
      ...u16(0), ...u16(0), ...u16(0), ...u16(0), ...u32(0), ...u32(offset), ...name,
    ]));
    offset += header.length + file.bytes.length;
  }
  const centralSize = central.reduce((sum, value) => sum + value.length, 0);
  const end = new Uint8Array([
    ...u32(0x06054b50), ...u16(0), ...u16(0), ...u16(files.length), ...u16(files.length),
    ...u32(centralSize), ...u32(offset), ...u16(0),
  ]);
  const output = new Uint8Array(offset + centralSize + end.length);
  let cursor = 0;
  for (const part of [...local, ...central, end]) {
    output.set(part, cursor);
    cursor += part.length;
  }
  return output;
}

interface GraphsViewProps {
  integration?: {
    session: GraphWebSession;
    initialGraphId?: string;
    onComplete: (result: CompleteGraphWebSessionResult) => void | Promise<void>;
    onCancel: () => void;
  };
}

export function GraphsView({ integration }: GraphsViewProps = {}) {
  const { showToast, confirm, setDirty, bumps } = useApp();
  const insertionTarget = integration?.session.problemId ? "問題" : "教材";
  const [graphs, setGraphs] = useState<StoredGraphSummary[]>([]);
  const [projects, setProjects] = useState<ProjectSummary[]>([]);
  const [record, setRecord] = useState<EditorRecord | null>(null);
  const [spatialStored, setSpatialStored] = useState<StoredGraph | null>(null);
  const [project, setProject] = useState<Project>(() => blankProject());
  const [warnings, setWarnings] = useState<Map<string, string>>(new Map());
  const [mathReady, setMathReady] = useState(false);
  const [selectedLabelId, setSelectedLabelId] = useState<string | null>(null);
  const [intersections, setIntersections] = useState<Intersection[]>([]);
  const [busy, setBusy] = useState(false);
  const [saveState, setSaveState] = useState<"saved" | "saving" | "dirty" | "error">("saved");
  const [pdfPreview, setPdfPreview] = useState<string | null>(null);
  const [selectedProjectId, setSelectedProjectId] = useState<number | "">("");
  const [graphVersions, setGraphVersions] = useState<GraphVersionSummary[] | null>(null);
  const [aiOpen, setAiOpen] = useState(false);
  const [aiMode, setAiMode] = useState<GraphAiMode>("graph-from-text");
  const [aiText, setAiText] = useState("");
  const [aiImage, setAiImage] = useState<File | null>(null);
  const [aiJob, setAiJob] = useState<AiJob | null>(null);
  const importRef = useRef<HTMLInputElement>(null);
  const parseCache = useRef(new Map<string, ParseResult>());
  const undoRef = useRef<Project[]>([]);
  const redoRef = useRef<Project[]>([]);
  const initialRouteOpenedRef = useRef(false);
  const integrationStartedRef = useRef(false);
  const projectRef = useRef(project);
  const recordRef = useRef(record);
  projectRef.current = project;
  recordRef.current = record;

  const reload = useCallback(async () => {
    try {
      const [graphRows, projectRows] = await Promise.all([listGraphs(), listProjects()]);
      setGraphs(graphRows);
      setProjects(projectRows);
    } catch (error) {
      showToast(String(error), "error");
    }
  }, [showToast]);

  useEffect(() => {
    void reload();
  }, [reload, bumps.graphs, bumps.projects]);

  useEffect(() => {
    let active = true;
    void initMathJax().then((ok) => active && setMathReady(ok));
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    if (!aiJob || !["queued", "preprocessing", "waiting_for_codex", "converting", "validating", "compiling"].includes(aiJob.status)) return;
    const timer = window.setTimeout(() => {
      void aiGetJob(aiJob.id).then(setAiJob).catch((error) => showToast(String(error), "error"));
    }, 1_000);
    return () => window.clearTimeout(timer);
  }, [aiJob, showToast]);

  useEffect(() => {
    if (integration || isTauri) return;
    const path = record
      ? `/graphs/${encodeURIComponent(record.id)}${pdfPreview ? "/export" : ""}`
      : "/graphs";
    if (window.location.pathname !== path) window.history.replaceState({}, "", path);
  }, [integration, record, pdfPreview]);

  const rendered: RenderItem[] = useMemo(
    () =>
      project.expressions.map((item) => {
        let parsed = parseCache.current.get(item.input);
        if (!parsed) {
          parsed = parseExpression(item.input);
          parseCache.current.set(item.input, parsed);
        }
        return { item, parsed };
      }),
    [project.expressions],
  );

  const aiPreview = useMemo(() => {
    const result = aiJob?.structuredResult ?? null;
    if (!isGraphResult(result)) return null;
    const decoded = deserializeProject(JSON.stringify(result.graphProject));
    if (!decoded.ok) return null;
    const items: RenderItem[] = decoded.project.expressions.map((item) => ({ item, parsed: parseExpression(item.input) }));
    return {
      project: decoded.project,
      svg: buildExportSvg(decoded.project, items, 760, 460),
      spec: result.graphSpec,
    };
  }, [aiJob]);

  const commit = useCallback((updater: (current: Project) => Project) => {
    setProject((current) => {
      const next = updater(current);
      if (next === current) return current;
      undoRef.current = [...undoRef.current.slice(-79), current];
      redoRef.current = [];
      return next;
    });
    setSaveState("dirty");
    setDirty(true);
  }, [setDirty]);

  const undo = useCallback(() => {
    const previous = undoRef.current.pop();
    if (!previous) return;
    redoRef.current.push(projectRef.current);
    setProject(previous);
    setSaveState("dirty");
  }, []);

  const redo = useCallback(() => {
    const next = redoRef.current.pop();
    if (!next) return;
    undoRef.current.push(projectRef.current);
    setProject(next);
    setSaveState("dirty");
  }, []);

  const save = useCallback(async (download = false): Promise<number | null> => {
    const currentRecord = recordRef.current;
    if (!currentRecord) return null;
    setSaveState("saving");
    try {
      const graphJson = serializeProject(projectRef.current);
      const title = projectRef.current.paper.title.trim() || currentRecord.title || "無題のグラフ";
      const version = await updateGraph({
        id: currentRecord.id,
        title,
        graphJson,
        graphType: "function_graph",
        sourceType: currentRecord.sourceType,
        warnings: [...warnings.values()],
        expectedVersion: currentRecord.version,
      });
      setRecord((value) => value && { ...value, title, version });
      setSaveState("saved");
      setDirty(false);
      if (download) {
        if (isTauri) downloadText(`${safeFileBase(title)}.graph.json`, graphJson, "application/json");
        else downloadUrl(graphFileUrl(currentRecord.id, "json", true));
      }
      void reload();
      return version;
    } catch (error) {
      setSaveState("error");
      showToast(
        error instanceof ConflictError
          ? "別の端末で更新されています。いったん一覧へ戻り、最新版を開き直してください。"
          : `保存に失敗しました: ${String(error)}`,
        "error",
      );
      return null;
    }
  }, [reload, setDirty, showToast, warnings]);

  useEffect(() => {
    if (!record || saveState !== "dirty") return;
    const timer = window.setTimeout(() => void save(false), 1_200);
    return () => window.clearTimeout(timer);
  }, [project, record, save, saveState]);

  useEffect(() => {
    const handler = (event: KeyboardEvent) => {
      if (!record) return;
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "s") {
        event.preventDefault();
        void save(false);
      } else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "z") {
        event.preventDefault();
        event.shiftKey ? redo() : undo();
      } else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "y") {
        event.preventDefault();
        redo();
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [record, redo, save, undo]);

  const open = async (id: string) => {
    setBusy(true);
    try {
      const stored = await getGraph(id);
      const spatialDecoded = parseSpatialDocument(stored.graphJson);
      if (spatialDecoded.ok) {
        setRecord(null);
        setSpatialStored(stored);
        setSaveState("saved");
        setDirty(false);
        return;
      }
      const decoded = deserializeProject(stored.graphJson);
      if (!decoded.ok) throw new Error(decoded.message);
      parseCache.current.clear();
      undoRef.current = [];
      redoRef.current = [];
      setProject(decoded.project);
      setSpatialStored(null);
      setRecord({ id: stored.id, title: stored.title, version: stored.version, sourceType: stored.sourceType });
      setWarnings(new Map(stored.warnings.map((warning, index) => [`saved-${index}`, warning])));
      setSelectedLabelId(null);
      setSaveState("saved");
      setDirty(false);
    } catch (error) {
      showToast(`グラフを開けません: ${String(error)}`, "error");
    } finally {
      setBusy(false);
    }
  };

  useEffect(() => {
    if (integration || isTauri || initialRouteOpenedRef.current) return;
    initialRouteOpenedRef.current = true;
    const match = window.location.pathname.match(/^\/graphs\/([A-Za-z0-9_-]+)(?:\/export)?$/);
    if (match) void open(match[1]);
    // 直リンクは初回だけ解決する。以後の遷移は画面状態が正本。
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [integration]);

  const createNew = async () => {
    setBusy(true);
    try {
      const initial = blankProject();
      const id = await createGraph({ title: "無題のグラフ", graphJson: serializeProject(initial) });
      await open(id);
      showToast("新しいグラフを作成しました");
    } catch (error) {
      showToast(`作成に失敗しました: ${String(error)}`, "error");
    } finally {
      setBusy(false);
    }
  };

  const createSpatial = async () => {
    setBusy(true);
    try {
      const initial = createTextbookCube();
      const id = await createGraph({
        title: initial.title,
        graphJson: serializeSpatialDocument(initial),
        graphType: "spatial_geometry",
      });
      await open(id);
      showToast("新しい空間図形を作成しました");
    } catch (error) {
      showToast(`空間図形の作成に失敗しました: ${String(error)}`, "error");
    } finally {
      setBusy(false);
    }
  };

  useEffect(() => {
    if (!integration || integrationStartedRef.current) return;
    integrationStartedRef.current = true;
    if (integration.initialGraphId) void open(integration.initialGraphId);
    // 新規の場合は一覧のモード選択を表示する。
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [integration?.session.sessionId]);

  const backToList = async () => {
    if (integration) {
      try {
        await cancelGraphWebSession(integration.session.sessionId);
      } catch (error) {
        showToast(`グラフ連携を終了できません: ${String(error)}`, "error");
        return;
      }
      integration.onCancel();
      return;
    }
    if (saveState === "dirty" || saveState === "saving") {
      const version = await save(false);
      if (
        version == null &&
        !(await confirm("保存に失敗しました。保存せずに一覧へ戻りますか？\n（このグラフの未保存の編集内容は失われます）"))
      ) {
        return;
      }
    }
    setRecord(null);
    setDirty(false);
    void reload();
  };

  const insertStoredGraph = async (graph: StoredGraphSummary) => {
    if (!integration || busy) return;
    if (!graph.exportsCurrent) {
      await open(graph.id);
      showToast(`最新の出力を作成してから「${insertionTarget}へ挿入して戻る」を押してください`);
      return;
    }
    setBusy(true);
    try {
      const result = await completeGraphWebSession(integration.session.sessionId, graph.id, graph.version);
      await integration.onComplete(result);
    } catch (error) {
      showToast(`${insertionTarget}へ挿入できません: ${String(error)}`, "error");
      await reload();
    } finally {
      setBusy(false);
    }
  };

  const exportArtifacts = async () => {
    const currentRecord = recordRef.current;
    if (!currentRecord) throw new Error("先にグラフを保存してください");
    const graphVersion = await save(false);
    if (graphVersion == null) throw new Error("グラフを保存できませんでした");
    await initMathJax();
    const ratio = graphAspectRatio(projectRef.current.paper, projectRef.current.range);
    const width = 1600;
    const height = Math.max(1, Math.round(width / ratio));
    const rawSvg = buildExportSvg(projectRef.current, rendered, width, height);
    const svg = svgFileContent(rawSvg);
    const png = await svgToPngBytes(rawSvg, 2);
    const doc = await buildPdf(projectRef.current, rendered);
    const pdf = new Uint8Array(doc.output("arraybuffer"));
    const tex = projectToPgfplots(projectRef.current);
    await saveGraphExports(currentRecord.id, {
      pdf: bytesToBase64(pdf),
      png: bytesToBase64(png),
      svg: bytesToBase64(new TextEncoder().encode(svg)),
      tex: bytesToBase64(new TextEncoder().encode(tex)),
    });
    return {
      pdf,
      png,
      svg,
      tex,
      json: serializeProject(projectRef.current),
      base: safeFileBase(projectRef.current.paper.title || currentRecord.title),
      version: graphVersion,
    };
  };

  const runExport = async (format: "pdf" | "png" | "svg" | "tex" | "zip") => {
    setBusy(true);
    try {
      const files = await exportArtifacts();
      if (format === "pdf") {
        const url = isTauri
          ? URL.createObjectURL(new Blob([files.pdf as BlobPart], { type: "application/pdf" }))
          : `${graphFileUrl(record!.id, "pdf")}?t=${Date.now()}`;
        setPdfPreview((old) => {
          if (old?.startsWith("blob:")) URL.revokeObjectURL(old);
          return url;
        });
      } else if (format === "png") {
        if (isTauri) downloadBytes(`${files.base}.png`, files.png, "image/png");
        else downloadUrl(graphFileUrl(record!.id, "png", true));
      } else if (format === "svg") {
        if (isTauri) downloadText(`${files.base}.svg`, files.svg, "image/svg+xml");
        else downloadUrl(graphFileUrl(record!.id, "svg", true));
      } else if (format === "tex") {
        if (isTauri) downloadText(`${files.base}.tex`, files.tex, "text/plain;charset=utf-8");
        else downloadUrl(graphFileUrl(record!.id, "tex", true));
      } else {
        if (isTauri) {
          const zip = makeZip([
            { name: "graph.pdf", bytes: files.pdf },
            { name: "graph.png", bytes: files.png },
            { name: "graph.svg", bytes: new TextEncoder().encode(files.svg) },
            { name: "graph.tex", bytes: new TextEncoder().encode(files.tex) },
            { name: "graph.json", bytes: new TextEncoder().encode(files.json) },
          ]);
          downloadBytes(`${files.base}.zip`, zip, "application/zip");
        } else {
          downloadUrl(graphFileUrl(record!.id, "zip", true));
        }
      }
      showToast("PC側へ保存し、現在の端末へ出力しました");
      void reload();
    } catch (error) {
      showToast(`出力に失敗しました: ${String(error)}`, "error");
    } finally {
      setBusy(false);
    }
  };

  const importFile = async (file: File) => {
    if (file.size > 2 * 1024 * 1024) {
      showToast("graph.jsonは2MBまでです", "error");
      return;
    }
    try {
      const text = await file.text();
      const spatial = parseSpatialDocument(text);
      if (spatial.ok) {
        const title = spatial.document.title || file.name.replace(/\.json$/i, "");
        const id = await createGraph({ title, graphJson: serializeSpatialDocument(spatial.document), graphType: "spatial_geometry", sourceType: "import" });
        await open(id);
        showToast("空間図形の編集JSONを読み込みました");
        return;
      }
      const decoded = deserializeProject(text);
      if (!decoded.ok) throw new Error(decoded.message);
      const title = decoded.project.paper.title || file.name.replace(/\.(mathgraph\.)?json$/i, "");
      const id = await createGraph({ title, graphJson: serializeProject(decoded.project), sourceType: "import" });
      await open(id);
      showToast("graph.jsonを読み込みました");
    } catch (error) {
      showToast(`読み込みに失敗しました: ${String(error)}`, "error");
    }
  };

  const startAiGraph = async () => {
    if (aiMode === "graph-from-image" && !aiImage) {
      showToast("分析する画像を選択してください", "error");
      return;
    }
    if (aiMode !== "graph-from-image" && !aiText.trim()) {
      showToast("グラフの条件または問題文を入力してください", "error");
      return;
    }
    setBusy(true);
    try {
      const inputNames: string[] = [];
      if (aiImage) {
        if (aiImage.size > 12 * 1024 * 1024) throw new Error("画像は12MBまでです");
        const uploaded = await aiStoreInputImage(bytesToBase64(new Uint8Array(await aiImage.arrayBuffer())), aiImage.name);
        inputNames.push(uploaded.name);
      }
      const job = await aiCreateJob({
        sourceType: aiMode === "graph-from-image" ? "image" : "text",
        conversionMode: aiMode,
        inputText: aiText.trim(),
        inputNames,
        options: { graphOutput: true, requireUserConfirmation: true },
      });
      setAiJob(job);
    } catch (error) {
      showToast(`AIグラフ生成を開始できません: ${String(error)}`, "error");
    } finally {
      setBusy(false);
    }
  };

  const acceptAiGraph = async () => {
    if (!aiPreview || !aiJob || !isGraphResult(aiJob.structuredResult)) return;
    setBusy(true);
    try {
      const sourceType = aiMode === "graph-from-image" ? "ai_image" : aiMode === "graph-from-problem" ? "ai_problem" : "ai_text";
      const id = await createGraph({
        title: aiPreview.project.paper.title || "AI生成グラフ",
        graphJson: serializeProject(aiPreview.project),
        sourceType,
        warnings: aiJob.warnings.map((warning) => warning.message),
      });
      setAiOpen(false);
      setAiJob(null);
      await open(id);
      showToast("AI結果を下書きとして編集画面へ読み込みました。確認後に保存・出力してください。");
    } catch (error) {
      showToast(`AI結果を読み込めません: ${String(error)}`, "error");
    } finally {
      setBusy(false);
    }
  };

  const addExpr = () => commit((p) => ({ ...p, expressions: [...p.expressions, defaultExprItem("", p.expressions.length)] }));
  const updateExpr = (id: string, patch: Partial<ExprItem>) => commit((p) => ({ ...p, expressions: p.expressions.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const removeExpr = (id: string) => commit((p) => ({ ...p, expressions: p.expressions.filter((item) => item.id !== id) }));
  const reorderExpr = (from: number, to: number) => commit((p) => {
    const expressions = [...p.expressions];
    const [moved] = expressions.splice(from, 1);
    if (!moved) return p;
    expressions.splice(to, 0, moved);
    return { ...p, expressions };
  });
  const updateRange = (patch: Partial<ViewRange>) => commit((p) => ({ ...p, range: { ...p.range, ...patch } }));
  const updatePaper = (patch: Partial<PaperSettings>) => commit((p) => ({ ...p, paper: { ...p.paper, ...patch } }));
  const addPoint = () => commit((p) => ({ ...p, points: [...p.points, { id: newId(), x: 0, y: 0, label: "", color: "#dc2626", visible: true, showProjectionToXAxis: false, showProjectionToYAxis: false }] }));
  const updatePoint = (id: string, patch: Partial<PointItem>) => commit((p) => ({ ...p, points: p.points.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const removePoint = (id: string) => commit((p) => ({ ...p, points: p.points.filter((item) => item.id !== id) }));
  const addLabel = () => commit((p) => ({ ...p, labels: [...p.labels, defaultLabel("y=x^2", (p.range.xmin + p.range.xmax) / 2, (p.range.ymin + p.range.ymax) / 2)] }));
  const updateLabel = (id: string, patch: Partial<MathLabel>) => commit((p) => ({ ...p, labels: p.labels.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const removeLabel = (id: string) => commit((p) => ({ ...p, labels: p.labels.filter((item) => item.id !== id) }));
  const moveLabel = (id: string, x: number, y: number) => updateLabel(id, { x, y });

  if (spatialStored) {
    return <SpatialGeometryEditor
      stored={spatialStored}
      projects={projects}
      integration={integration ? { session: integration.session, onComplete: integration.onComplete, onCancel: integration.onCancel } : undefined}
      onReload={reload}
      onClose={async () => {
        if (integration) {
          try { await cancelGraphWebSession(integration.session.sessionId); }
          catch (error) { showToast(`グラフ連携を終了できません: ${String(error)}`, "error"); return; }
          integration.onCancel();
        } else {
          setSpatialStored(null);
          setDirty(false);
          void reload();
        }
      }}
    />;
  }

  if (!record) {
    return (
      <>
      <div className="graphs-list h-full overflow-y-auto p-4">
        <div className="mb-4 flex flex-wrap items-center gap-2">
          <div>
            <h2 className="text-base font-bold">グラフ・空間図形</h2>
            <p className="text-xs" style={{ color: "var(--muted)" }}>2Dグラフと教材用の3D空間図形を、同じ保存・教材連携で管理します。</p>
          </div>
          <span className="ml-auto" />
          <input ref={importRef} type="file" accept=".json,.mathgraph.json,application/json" hidden onChange={(event) => {
            const file = event.target.files?.[0];
            event.currentTarget.value = "";
            if (file) void importFile(file);
          }} />
          <button className="btn btn-outline" onClick={() => { setAiOpen(true); setAiJob(null); }}>AIで作成</button>
          <button className="btn btn-outline" onClick={() => importRef.current?.click()}>graph.jsonを読み込む</button>
          {integration && <button className="btn btn-ghost" onClick={() => void backToList()}>キャンセル</button>}
          <button className="btn btn-primary" disabled={busy} onClick={() => void createNew()}>＋ 2Dグラフ</button>
          <button className="btn btn-primary" disabled={busy} onClick={() => void createSpatial()}>＋ 空間図形</button>
        </div>
        {graphs.length === 0 ? (
          <div className="empty-state">保存済みのグラフはありません。</div>
        ) : (
          <div className="graphs-grid">
            {graphs.map((graph) => (
              <article key={graph.id} className="graph-card">
                <button className="graph-card-preview" onClick={() => void open(graph.id)}>
                  {!isTauri && graph.thumbnailPath ? (
                    <img src={`${graph.thumbnailPath}?v=${graph.version}`} alt={`${graph.title}のプレビュー`} loading="lazy" />
                  ) : (
                    <><span className="text-4xl" aria-hidden>⌁</span><span>編集データ</span></>
                  )}
                </button>
                <div className="min-w-0 flex-1">
                  <button className="block max-w-full truncate text-left text-sm font-semibold" onClick={() => void open(graph.id)}>{graph.title}</button>
                  <div className="mt-1 text-[11px]" style={{ color: "var(--muted)" }}>
                    v{graph.version} ・ {graph.updatedAt} ・ 教材使用 {graph.usageCount}件
                  </div>
                  <div className="mt-2 flex flex-wrap gap-1">
                    <span className="badge">{graph.graphType === "spatial_geometry" ? "空間図形" : "2Dグラフ"}</span>
                    {graph.savedFormats.map((format) => <span key={format} className="badge">{format.toUpperCase()}</span>)}
                    {graph.warnings.length > 0 && <span className="badge badge-warn">警告 {graph.warnings.length}</span>}
                  </div>
                </div>
                <div className="flex shrink-0 flex-col gap-1">
                  {integration && <button className="btn btn-sm btn-primary" disabled={busy} onClick={() => void insertStoredGraph(graph)}>{graph.exportsCurrent ? `そのまま${insertionTarget}へ挿入` : "開いて挿入"}</button>}
                  <button className="btn btn-sm" onClick={() => void open(graph.id)}>開く</button>
                  <button className="btn btn-sm btn-ghost" onClick={async () => {
                    try { await duplicateGraph(graph.id); await reload(); showToast("複製しました"); } catch (error) { showToast(String(error), "error"); }
                  }}>複製</button>
                  <button className="btn btn-sm btn-ghost" onClick={async () => {
                    if (!(await confirm(`「${graph.title}」をゴミ箱へ移動しますか？\n教材に挿入済みのスナップショットは変更されません。`))) return;
                    try { await deleteGraph(graph.id, graph.version); await reload(); } catch (error) { showToast(String(error), "error"); }
                  }}>削除</button>
                </div>
              </article>
            ))}
          </div>
        )}
      </div>
      {aiOpen && (
        <Modal title="Codexでグラフ設定を作成" wide onClose={() => {
          if (aiJob && ["queued", "preprocessing", "waiting_for_codex", "converting", "validating"].includes(aiJob.status)) void aiCancelJob(aiJob.id);
          setAiOpen(false);
        }}>
          <div className="grid gap-4 md:grid-cols-[minmax(260px,0.85fr)_minmax(320px,1.15fr)]">
            <div className="flex flex-col gap-3">
              <div className="grid grid-cols-3 gap-1">
                {([
                  ["graph-from-text", "テキスト"],
                  ["graph-from-image", "写真"],
                  ["graph-from-problem", "問題文"],
                ] as const).map(([mode, label]) => (
                  <button key={mode} className={`btn ${aiMode === mode ? "btn-outline" : "btn-ghost"}`} onClick={() => { setAiMode(mode); setAiJob(null); }}>{label}</button>
                ))}
              </div>
              {aiMode === "graph-from-image" ? (
                <label className="rounded border border-dashed p-3 text-xs" style={{ borderColor: "var(--border-strong)" }}>
                  <span className="mb-2 block">参考書・プリント・手書き図の画像</span>
                  <input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setAiImage(event.target.files?.[0] ?? null)} />
                  {aiImage && <span className="mt-2 block" style={{ color: "var(--muted)" }}>{aiImage.name}</span>}
                </label>
              ) : (
                <label>
                  <span className="mb-1 block text-xs">{aiMode === "graph-from-problem" ? "グラフを必要とする問題文" : "関数・範囲・表示したい点やラベル"}</span>
                  <textarea
                    className="input min-h-44 resize-y text-sm"
                    value={aiText}
                    placeholder={aiMode === "graph-from-problem" ? "問題文を貼り付けてください" : "例: y=x^2-4x+3。頂点とx軸との交点を表示。xは-2から6。方眼なし。"}
                    onChange={(event) => setAiText(event.target.value)}
                  />
                </label>
              )}
              {aiMode === "graph-from-image" && (
                <label>
                  <span className="mb-1 block text-xs">補足（任意）</span>
                  <textarea className="input min-h-20 text-sm" value={aiText} onChange={(event) => setAiText(event.target.value)} />
                </label>
              )}
              <div className="rounded p-2 text-[11px] leading-relaxed" style={{ background: "var(--panel-2)", color: "var(--muted)" }}>
                AIは編集可能な設定だけを返します。結果はここで確認するまでグラフ一覧へ保存されません。不鮮明な箇所は警告として残ります。
              </div>
              <button className="btn btn-primary" disabled={busy || !!aiJob && ["queued", "preprocessing", "waiting_for_codex", "converting", "validating"].includes(aiJob.status)} onClick={() => void startAiGraph()}>
                {aiJob && !["completed", "failed", "cancelled"].includes(aiJob.status) ? aiJob.progressMessage || "生成中…" : "グラフ設定を生成"}
              </button>
              {aiJob?.status === "failed" && <div className="err-msg">{aiJob.errorMessage || "生成に失敗しました"}</div>}
            </div>
            <div className="min-h-[360px] rounded border p-3" style={{ borderColor: "var(--border)", background: "#11131a" }}>
              {!aiPreview ? (
                <div className="flex h-full min-h-[330px] items-center justify-center text-xs" style={{ color: "var(--muted)" }}>
                  {aiJob ? aiJob.progressMessage || aiJob.status : "生成結果のグラフと設定がここに表示されます"}
                </div>
              ) : (
                <div className="flex h-full flex-col gap-3">
                  <div className="graph-ai-preview" dangerouslySetInnerHTML={{ __html: aiPreview.svg }} />
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div>式: {aiPreview.spec.expressions.map((value) => value.expression).join(" / ") || "なし"}</div>
                    <div>範囲: x {aiPreview.spec.viewport.xMin}〜{aiPreview.spec.viewport.xMax}, y {aiPreview.spec.viewport.yMin}〜{aiPreview.spec.viewport.yMax}</div>
                    <div>点: {aiPreview.spec.points.length}件</div>
                    <div>ラベル: {aiPreview.spec.labels.length}件</div>
                  </div>
                  {(aiJob?.warnings.length ?? 0) > 0 && (
                    <div className="warn-msg">{aiJob?.warnings.map((warning) => warning.message).join("\n")}</div>
                  )}
                  {(aiJob?.uncertainFragments.length ?? 0) > 0 && (
                    <div className="warn-msg">要確認: {aiJob?.uncertainFragments.map((value) => value.description).join(" / ")}</div>
                  )}
                  <div className="mt-auto flex flex-wrap justify-end gap-2">
                    <button className="btn" onClick={() => { setAiJob(null); void startAiGraph(); }}>再解析</button>
                    <button className="btn btn-primary" disabled={busy} onClick={() => void acceptAiGraph()}>確認して編集画面へ読み込む</button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </Modal>
      )}
      </>
    );
  }

  return (
    <div className="graph-editor h-full min-h-0">
      <div className="graph-editor-toolbar">
        <button className="btn btn-sm" onClick={() => void backToList()}>
          {integration ? "キャンセル" : "← 一覧"}
        </button>
        <input
          className="input graph-title-input"
          value={project.paper.title}
          placeholder={record.title || "グラフのタイトル"}
          onChange={(event) => updatePaper({ title: event.target.value })}
        />
        <span className={`save-indicator save-${saveState}`}>
          {saveState === "saved" ? "保存済み" : saveState === "saving" ? "保存中…" : saveState === "error" ? "保存失敗" : "未保存"}
        </span>
        <button className="btn btn-sm" disabled={undoRef.current.length === 0} onClick={undo}>Undo</button>
        <button className="btn btn-sm" disabled={redoRef.current.length === 0} onClick={redo}>Redo</button>
        <button className="btn btn-sm" onClick={async () => {
          try { setGraphVersions(await listGraphVersions(record.id)); }
          catch (error) { showToast(`履歴を取得できません: ${String(error)}`, "error"); }
        }}>履歴</button>
        <button className="btn btn-sm" disabled={busy} onClick={() => void runExport("tex")}>TikZ</button>
        <button className="btn btn-sm" disabled={busy} onClick={() => void runExport("zip")}>一式ZIP</button>
        {integration ? (
          <button className="btn btn-sm btn-primary" disabled={busy} onClick={async () => {
            setBusy(true);
            try {
              const files = await exportArtifacts();
              const result = await completeGraphWebSession(
                integration.session.sessionId,
                record.id,
                files.version,
              );
              await integration.onComplete(result);
            } catch (error) {
              showToast(`教材へ挿入できません: ${String(error)}`, "error");
            } finally {
              setBusy(false);
            }
          }}>{insertionTarget}へ挿入して戻る</button>
        ) : (
          <>
            <select className="input graph-project-select" value={selectedProjectId} onChange={(event) => setSelectedProjectId(event.target.value ? Number(event.target.value) : "")}>
              <option value="">教材を選択…</option>
              {projects.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}
            </select>
            <button className="btn btn-sm btn-primary" disabled={busy || selectedProjectId === ""} onClick={async () => {
              if (selectedProjectId === "") return;
              setBusy(true);
              try {
                await exportArtifacts();
                const target = projects.find((value) => value.id === selectedProjectId);
                await insertGraphToProject(record.id, selectedProjectId, target?.version);
                await reload();
                showToast("教材へグラフをスナップショットとして挿入しました");
              }
              catch (error) { showToast(`教材へ挿入できません: ${String(error)}`, "error"); }
              finally { setBusy(false); }
            }}>教材へ挿入</button>
          </>
        )}
      </div>

      <div className="graph-editor-layout">
        <aside className="graph-expressions panel">
          <ExpressionPanel
            items={rendered} points={project.points} labels={project.labels}
            selectedLabelId={selectedLabelId} mathReady={mathReady} warnings={warnings}
            onAdd={addExpr} onUpdate={updateExpr} onRemove={removeExpr} onReorder={reorderExpr}
            onAddPoint={addPoint} onUpdatePoint={updatePoint} onRemovePoint={removePoint}
            onAddLabel={addLabel} onUpdateLabel={updateLabel} onRemoveLabel={removeLabel}
            onSelectLabel={setSelectedLabelId}
          />
        </aside>
        <main className="graph-stage">
          <GraphView
            items={rendered} points={project.points} labels={project.labels} range={project.range}
            paper={project.paper} mathReady={mathReady} selectedLabelId={selectedLabelId}
            onRangeChange={updateRange} onWarningsChange={setWarnings} onLabelMove={moveLabel}
            onSelectLabel={setSelectedLabelId} onIntersectionsChange={setIntersections}
          />
        </main>
        <aside className="graph-settings panel">
          <SettingsPanel
            range={project.range} paper={project.paper} intersections={intersections} busy={busy}
            onRangeChange={updateRange} onPaperChange={updatePaper}
            onPdf={() => void runExport("pdf")} onPng={() => void runExport("png")} onSvg={() => void runExport("svg")}
            onSaveProject={() => void save(true)} onOpenProject={() => importRef.current?.click()}
            onNewProject={() => void createNew()}
          />
        </aside>
      </div>
      <input ref={importRef} type="file" accept=".json,.mathgraph.json,application/json" hidden onChange={(event) => {
        const file = event.target.files?.[0]; event.currentTarget.value = ""; if (file) void importFile(file);
      }} />

      {pdfPreview && (
        <Modal title="グラフPDFプレビュー" wide onClose={() => { if (pdfPreview.startsWith("blob:")) URL.revokeObjectURL(pdfPreview); setPdfPreview(null); }}>
          <div className="h-[70vh] min-h-[360px]">
            <PdfCanvasViewer src={pdfPreview} zoom={100} />
          </div>
          <div className="mt-3 flex justify-end">
            <button className="btn btn-primary" onClick={async () => {
              if (!isTauri) {
                downloadUrl(graphFileUrl(record.id, "pdf", true));
                return;
              }
              const response = await fetch(pdfPreview);
              const bytes = new Uint8Array(await response.arrayBuffer());
              downloadBytes(`${safeFileBase(project.paper.title || record.title)}.pdf`, bytes, "application/pdf");
            }}>PDFをこの端末へ保存</button>
          </div>
        </Modal>
      )}

      {graphVersions && (
        <Modal title="グラフの更新履歴" onClose={() => setGraphVersions(null)}>
          {graphVersions.length === 0 ? (
            <p className="text-sm" style={{ color: "var(--muted)" }}>まだ過去版はありません。</p>
          ) : (
            <div className="max-h-[60vh] space-y-2 overflow-y-auto">
              {graphVersions.map((version) => (
                <div key={version.id} className="card flex items-center gap-3 p-3">
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-sm font-semibold">v{version.version}・{version.title}</div>
                    <div className="mt-1 text-xs" style={{ color: "var(--muted)" }}>{version.savedAt}</div>
                  </div>
                  <button className="btn btn-sm btn-outline" onClick={async () => {
                    if (!(await confirm(`v${version.version} を復元しますか？\n現在版は履歴へ保存されます。`))) return;
                    try {
                      await restoreGraphVersion(version.id, record.version);
                      setGraphVersions(null);
                      await open(record.id);
                      showToast(`v${version.version}を新しい版として復元しました`);
                    } catch (error) {
                      showToast(`復元できません: ${String(error)}`, "error");
                    }
                  }}>この版を復元</button>
                </div>
              ))}
            </div>
          )}
        </Modal>
      )}
    </div>
  );
}
